hello: ENC[AES256_GCM,data:sRLI97cKXC8OQiNNMQy3U2O0rjjHGxPJD/y4KWtvt9cmzpvoQKlvdWg3OhQ2iQ==,iv:w3sfxe7w+nPWaUDPkuz8ztUArPbEhWHMAP0INiAvYDA=,tag:GfmXOdSAu6rGn2uy5ZTZmg==,type:str]
example_key: ENC[AES256_GCM,data:e5BdyFQRn+WE3xzk9A==,iv:si53+B9vUesPc+hS0X7XjOOLk3Fzab5e9JyirENqlh8=,tag:f2ba1Vo86cWNhR+JU2ITNA==,type:str]
#ENC[AES256_GCM,data:bIOXqEQuH+l1wL0tfhuOzg==,iv:2xrP0Bb57AvK536Qje5iuY+d1/R0MtXqXDGnZpNCrko=,tag:mnPmUV4fGErdWakqeunY4Q==,type:comment]
example_array:
    - ENC[AES256_GCM,data:7Uj8lPH8SDHgKx0QRSQ=,iv:pCGRPVmmg2UfA3Z5NEebUI5ha2PieKaISkWoume6Vgw=,tag:6y8Oyo/Kdu4mGZcfkJ14dA==,type:str]
    - ENC[AES256_GCM,data:1g8ygN2Y9WAAXfbcvQ4=,iv:fgCQImBuZNhKzoF5K8e4PGLxvCM12Gpolk3G9OzGeys=,tag:n1QnA5Q0JoP8fH/qj8PAXQ==,type:str]
example_number: ENC[AES256_GCM,data:1EywrC+v1NIQbQ==,iv:jpwXjbzehK3P8fzqDMlroyBliOi5gJ+xvlfK2950Czk=,tag:elioUvFvpUO+wt+nmHfgMA==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5apq38d9vs8q7u6ahkhcut2p2w3eyprdskp0s8f7tsxr8s8tpgsqfa6te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV2F2a1N6aGVJNHZ1V3Vh
            T3NoM0tlNlNqanF3Q1BzeWJCYUc2YmVmUFdrCjZNMDM4dU5EUWJIN2VQYmMxeGlj
            Mld4VEROZGIwZGxEajhzQXpaTFpCVmsKLS0tIGZVN3dlWXRmT0JzdTRxbkY5djE3
            UDNCSTR4c1NyZGUrc1BCNmpSSFkwMVkKRtilEn8Icq92JBQf7415seTS19yovq86
            g4GleNUOfgX2nNYABiLTeXOm3nnqjbGLP/p/fJ9D1bfWNaix9UHYDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T14:52:29Z"
    mac: ENC[AES256_GCM,data:KJ/V7jl76rSgcpdHabIEopimtViBcaYbSx24+M/MwnKY7vsgAdA3TM/j9JuC0mPnTZ9tfGTRVhkYUSzigjI4QR/GtSeVWEFK7ovuabG/8cN3IDC2RafW9yhucvS5kmu+U2jlHXxh68i9lw8FYq6zIW3mFkqK7iaME8KHCMK7Eko=,iv:TXmdqKtdXZQOwm7G2kYWSCy2AyUgnKoUJKJkEhRv+84=,tag:WbeMNdh1N1BMs93LwEZj+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
