hello: ENC[AES256_GCM,data:nOlf28vwnveXb7uoC7VLCaFl6Wjr7qgOsHSokRa4yuzTOujFKL5QPHSMY6nwwg==,iv:+TX7/LGiKPX9YhBo/mOFd/jS7u7J5OGPtNHPgVDuULM=,tag:Oeec6dmi6LaTCOFzYWQNnA==,type:str]
example_key: ENC[AES256_GCM,data:qTa7/x+5OembYWGKRQ==,iv:UHIkFTJh+SDlN4VSFsHoh4EJy22zLJjA1xTJkniak7M=,tag:aKe9c49XH6gKZs3Q6kZGjQ==,type:str]
#ENC[AES256_GCM,data:i1m3BhJNVJMgsNk9rXqIQQ==,iv:iHmQTIZcC6zBYiKv8+cqv0Z8xGD+AGvZ+FVGKxqdeEQ=,tag:/76tjEUSLv2l0fIUS8oQrw==,type:comment]
example_array:
    - ENC[AES256_GCM,data:oU6fNykIEQdlPb8fENU=,iv:72cNoeYOcNodQyjZdjL4ta74S51z8C0oAQL/08wuFYo=,tag:cjzURUOGbm62N05iciz/xA==,type:str]
    - ENC[AES256_GCM,data:pMDgTKDH7CDMS2cLD2M=,iv:JiXCHuz1nj3R6ywZKbyHBV3rez1viDExZguDfhwz9Rk=,tag:xXtgkoyegXGUWLiXPfYy2A==,type:str]
example_number: ENC[AES256_GCM,data:zi/OSdwm6ioevA==,iv:/RZ/7lNxz+0GjmUJPAwbwqpc+ilQdvRmBg+P99Lt2dY=,tag:WszOhXgaBZwwTxXgzAUsig==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l8ul4havjmpsjqsnc3efcs4xapahkffx6tkah02qplu6k4ryncjsn3g95g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjandaR1M5YStOMWxtdzVP
            WjFZUW5wTENrMitMVitwbVNJN3pZaUxXTURBCmZkSEZjNmhkb1duY0hWcnR4clp0
            aGFRZ2lWSDFma1ozS0lWSngvVEswUUEKLS0tIDFIc1hCdE42eWJiUDl0bkQ4czZG
            NElNSm1MWWpabGNleWVvQ28rM2hSM1kKriaRgO2pSQtDNEufF4WJcLPw/Jo/oyN/
            R8vNp6AAQMW8NHDXW3JmKU8+c18HamoUReKVRyMbXPAxDNmIBmsKlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nxs9wm7mf0nu3h8270jmjw3pl2cuwwfxqqe8px48gqs5l47wuassueasu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONjNmTlVJMTBabjZWeS9q
            aXVHZTZZelZsTlN4S3hUZWZ5STFPejFVZG00Clc0ZnViTDRmR2F4c2FzTTBuZ2k2
            NERXTjd0S3JvaThGdTlPVDFlaVJxTjgKLS0tIGhPcEg2bFVyTjVDbFRNM0IxeUIy
            SkZ6R051VFN5WFFTa2tBTUNzVUIwTUEKdw9S4pnYzqMr0oOUKLaf+LzXRPlZ5kuK
            VmGkQQ9lLLh+6Bg3LRQmBI4uyixGCLBGpRPa6Vb9npF2JxzuRforeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T15:57:00Z"
    mac: ENC[AES256_GCM,data:nBQnCwrgYcas6KMO6UMM8rSUpb7gHpbTwZgjT7s9N8cgV3Ei4zU6V3d0N+Tx5Csz9iOpuP0klqewhW5EsN0iiqflR2/p8X0S/jOMDXaIeQ4X7CFw7IV5lDgGbovNpFGH1K+MB11Q73cRQK8of0dIKgRRv9w7O+mzGJzWDRADWZI=,iv:sdm7JM0bZ/7CSfQEvtwnVP8I6+RZ1CE6AVDdyPJn00Y=,tag:vCXi25Cy/4Z+mpIN05PZhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
