hello: ENC[AES256_GCM,data:zFVpHR4Cc1Z0QyAfyvX3Xw+58DidY+dU09VIkhXAwq7jeFPHHXnWzrDvNxbpEA==,iv:u/DDX53Wq1zYyqyFlV7+ruHjh8t16wulfUOFpY6ecmE=,tag:H0TCIMN7+SnvRc1PPZZJFw==,type:str]
example_key: ENC[AES256_GCM,data:v+OGIfUYS8XGUaU/uA==,iv:GVeDoD7/r9OEjSuqzp75o4Zbwj3pmcV+8iJw13ywvAo=,tag:RQmwxpHJxbAHHIqI0ca+sg==,type:str]
#ENC[AES256_GCM,data:5doif8cC5AhyZHPnLjGSkw==,iv:r9mD2UrTm5m6bZUO+lNyhmlvOFhRAe77jajOHac0f8U=,tag:6O44R0qXFwWcumirsTPwEQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:McolOmst8jcV6z2e5gY=,iv:A5JcJkb/6TQZdQTlINYnfvMLyiEFEX4UGZnIy49p0zg=,tag:jj80/Ur5f4JwhqjxZUCnaw==,type:str]
    - ENC[AES256_GCM,data:f46lUyDpc7xQX9h+QCo=,iv:b8uLV/ebV4L1P21Jt2zdLSfxttS8YltERVsX4YsJYr0=,tag:K2qEGM1Ak9o6Q+aOroFPAg==,type:str]
example_number: ENC[AES256_GCM,data:wtjhcViur2AN+Q==,iv:rg4xB+xt2XZWCMZsXlv4xntrcWor9zUDREy7D0bsjjE=,tag:8V2/BWHE3OnMc3xuXhmpSA==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tysj2hv90pzyze0kclxs8htey3udqlej7cstshqc8v9z8ah3z49se8khu4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHVIM2NaM1E1YXUvN2Nx
            S2p5dDVyWmF6MmlPR2wwQVFUc29GR0psWEF3CkNuVGFaM0J3aWpaWFA5QzNTY3Nm
            dFNTMGZRbXBHUjFYWHpDVTdBRG4ybEUKLS0tIDlFb1RvSzBEU01EQytwWVE3ZGdQ
            UVRzdDU3S0dVRUMvVzQ0ZVpjTmxFK0EK8UooW7i/VL/jsOZQpfCm6mfdpS6OKABT
            qy03ixzi9jllY26rAg/s+k1Fuv6edAXbGXWoIIE0FT346lPgrBlM1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T15:09:11Z"
    mac: ENC[AES256_GCM,data:PH5Blyi8TzOgT5JCwUt+Lyi3Bw3HmHte/Eeg4pWz1Kx1Xu8ifYs0/MlCPBSovxTUZccLRfHfIAiofAPEzWZbBQURHcqHdZL3PTIo4QF/MemL2qQzZurI4vT2tJy00c6cqMt6rAWwvgS1gyQBLlCw/o6BxOZkaKJ21IrNFOzt+lw=,iv:Vxu3lrSrJHklBUH7hkcaBE/mg31wy9v5KCSNEqwAClQ=,tag:mXHi4m42W3DBHQR5YccCcg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
